CREATE TABLE SHOP (
	SHOP 		  INT PRIMARY KEY AUTO_INCREMENT NOT NULL ,
	SHOPW_NAME VARCHAR(30) NOT NULL
)ENGINE=InnoDB DEFAULT CHARACTER SET UTF8 COLLATE UTF8_GENERAL_CI;


CREATE TABLE ADMIN(
	ADMIN_ID 	VARCHAR(30) PRIMARY KEY NOT NULL,
	SHOP_NO		INT			NOT NULL,
	PASSWORD 	VARCHAR(30) NOT NULL,
	NAME			VARCHAR(30) NOT NULL,
	SEX 			VARCHAR(2)  NOT NULL,
	PHONE 		VARCHAR(20) NOT NULL,
	AGE 			INT			NOT NULL,
	INSERT_DATE TIMESTAMP DEFAULT NOW(),
	DELETE_DAET TIMESTAMP DEFAULT NOW()
)ENGINE=InnoDB DEFAULT CHARACTER SET UTF8 COLLATE UTF8_GENERAL_CI;

CREATE TABLE SALES(
	SALES_NO 	INT PRIMARY KEY NOT NULL,
	ADMIN_ID 	VARCHAR(30) NOT NULL,
	INCOME		INT NOT NULL,
	MEMO 	 		TEXT NOT NULL,
	INSERT_DATE TIMESTAMP DEFAULT NOW()
)ENGINE=InnoDB DEFAULT CHARACTER SET UTF8 COLLATE UTF8_GENERAL_CI;

CREATE TABLE DAY_OFF (
	DAY_OFF 			VARCHAR(30) PRIMARY KEY NOT NULL,
	DAY_OFF_DATE 	TIMESTAMP DEFAULT NOW(),
	INSERT_DATE 	TIMESTAMP DEFAULT NOW(),
	ADMIN_ID			VARCHAR(30) NOT NULL
)ENGINE=InnoDB DEFAULT CHARACTER SET UTF8 COLLATE UTF8_GENERAL_CI;

CREATE TABLE USER (
	USER_ID 			VARCHAR(30) PRIMARY KEY NOT NULL,
	PASSWORD			VARCHAR(30) NOT NULL,
	NAME				VARCHAR(30) NOT NULL,
	SEX				VARCHAR(2) 	NOT NULL,
	PHONE				VARCHAR(20) NOT NULL,
	AGE				INT			NOT NULL,
	INSERT_DATE		TIMESTAMP	DEFAULT NOW(),
	DELETE_DATE		TIMESTAMP	DEFAULT NOW()
)ENGINE=InnoDB DEFAULT CHARACTER SET UTF8 COLLATE UTF8_GENERAL_CI;

CREATE TABLE USER_DETAIL (
	USER_DETAIL_NO		INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
	MEMO					TEXT NOT NULL,
	COUNT					INT DEFAULT 0,
	INSERT_DATE			TIMESTAMP DEFAULT NOW(),
	USER_ID				VARCHAR(30) NOT NULL
)ENGINE=InnoDB DEFAULT CHARACTER SET UTF8 COLLATE UTF8_GENERAL_CI;

CREATE TABLE REVIEW (
	REVIEW_NO			INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
	REVIEW_TITLE		VARCHAR(50) NOT NULL,
	REVIEW_CONTENT		TEXT NOT NULL,
	STARS					INT DEFAULT 0,
	INSERT_DATE			TIMESTAMP DEFAULT NOW(),
	SERVICE_NO			INT NOT NULL,
	USER_ID				VARCHAR(30) NOT NULL,
	ADMIN_ID				VARCHAR(30) NOT NULL
)ENGINE=InnoDB DEFAULT CHARACTER SET UTF8 COLLATE UTF8_GENERAL_CI;

CREATE TABLE MEMBERSHIP (
	MEMBERSHIP_NO		INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
	MEMO					TEXT NOT NULL,
	INSERT_DATE			TIMESTAMP DEFAULT NOW(),
	USER_ID				VARCHAR(30)
)ENGINE=InnoDB DEFAULT CHARACTER SET UTF8 COLLATE UTF8_GENERAL_CI;


CREATE TABLE MEMBERSHIP_USAGE ( 
	USAGE_NO 			INT 	PRIMARY KEY AUTO_INCREMENT NOT NULL,
	PRICE					INT 	NOT NULL,
	DESCRIPTION			TEXT 	NOT NULL,
	MEMBERSHIP_NO		INT 	NOT NULL
)ENGINE=InnoDB DEFAULT CHARACTER SET UTF8 COLLATE UTF8_GENERAL_CI;


CREATE TABLE RESERVATION (
	RESERVATION_NO			INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
	RESERVATION_DATE		TIMESTAMP DEFAULT NOW(),
	IS_CONFIRM				VARCHAR(1)	DEFAULT 'N',
	MEMO						TEXT	NOT NULL,
	INSERT_DATE				TIMESTAMP DEFAULT NOW(),
	SERVICE_NO				INT	NOT NULL,
	ADMIN_ID					VARCHAR(30) NOT NULL,
	USER_ID					VARCHAR(30) NOT NULL
)ENGINE=InnoDB DEFAULT CHARACTER SET UTF8 COLLATE UTF8_GENERAL_CI;


CREATE TABLE SERVICE (
	SERVICE_NO 				INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
	SERVICE_NAME			VARCHAR(30) NOT NULL,
	SERVICE_PRICE			INT NOT NULL,
	MEMO						TEXT NOT NULL
)ENGINE=InnoDB DEFAULT CHARACTER SET UTF8 COLLATE UTF8_GENERAL_CI;

